# Generated by Django 4.2.5 on 2023-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'EmailCode',
                'verbose_name_plural': 'EmailCodes',
            },
        ),
        migrations.AlterModelOptions(
            name='bundle',
            options={'verbose_name': 'Bundle', 'verbose_name_plural': 'Bundles'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'Subsection', 'verbose_name_plural': 'Subsections'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'verbose_name': 'Tender', 'verbose_name_plural': 'Tenders'},
        ),
        migrations.AlterModelOptions(
            name='tenderdoc',
            options={'verbose_name': 'TenderDoc', 'verbose_name_plural': 'TenderDocs'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AlterModelOptions(
            name='workerdoc',
            options={'verbose_name': 'WorkerDoc', 'verbose_name_plural': 'WorkerDocs'},
        ),
    ]
