# Generated by Django 4.2.5 on 2023-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0002_emailcode_alter_bundle_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('company', 'company'), ('worker', 'worker'), ('admin', 'admin')], max_length=55),
        ),
    ]
