# Generated by Django 4.2.5 on 2023-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0004_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='is_registered',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expired_date',
            field=models.DateField(),
        ),
    ]
